version: '3'

services:
  backend:
    build: ./backend
    environment:
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=Shopper
      - DB_HOST=db
      - PORT=3001
    volumes:
      - ./backend:/app-backend
    restart: always
    ports:
      - 3001:3001

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./frontend:/app-frontend
  
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    restart: always